#pragma once

#include <cstddef>
#include <cstdint>

enum class GearSetKind {
    Rider,
    Bike
};

enum class GearSetSlot {
    RiderTop,
    RiderBottom,
    RiderHelmet,
    BikeFairings,
    BikeWheels
};

struct GearSetCatalogEntry {
    uint16_t id;
    GearSetKind kind;
    GearSetSlot slot;
    const char* genKey;
    const char* category;
    uint8_t colorPartCount;
};

static const GearSetCatalogEntry kGearSetCatalog[] = {
    { 1, GearSetKind::Rider, GearSetSlot::RiderTop, "TECHBOY_TOP_1", "TOP", 1 },
    { 2, GearSetKind::Rider, GearSetSlot::RiderTop, "TECHBOY_TOP_2", "TOP", 1 },
    { 3, GearSetKind::Rider, GearSetSlot::RiderTop, "TECHBOY_TOP_4", "TOP", 1 },
    { 4, GearSetKind::Rider, GearSetSlot::RiderBottom, "TECHBOY_BOTTOM_1", "BOTTOM", 1 },
    { 5, GearSetKind::Rider, GearSetSlot::RiderBottom, "TECHBOY_BOTTOM_2", "BOTTOM", 1 },
    { 6, GearSetKind::Rider, GearSetSlot::RiderBottom, "TECHBOY_BOTTOM_4", "BOTTOM", 1 },
    { 7, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TECHBOY_HELMET_1", "HELMET", 1 },
    { 8, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TECHBOY_HELMET_2", "HELMET", 1 },
    { 9, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TECHBOY_HELMET_4", "HELMET", 1 },
    { 10, GearSetKind::Rider, GearSetSlot::RiderHelmet, "SQUIRREL_HELMET_1", "HELMET", 0 },
    { 11, GearSetKind::Rider, GearSetSlot::RiderTop, "EVEL_TOP_1", "TOP", 1 },
    { 12, GearSetKind::Rider, GearSetSlot::RiderHelmet, "EVEL_HELMET_1", "HELMET", 1 },
    { 13, GearSetKind::Rider, GearSetSlot::RiderBottom, "EVEL_BOTTOM_1", "BOTTOM", 1 },
    { 14, GearSetKind::Rider, GearSetSlot::RiderTop, "DIRTRUNNER_TOP_1", "TOP", 1 },
    { 15, GearSetKind::Rider, GearSetSlot::RiderTop, "DIRTRUNNER_TOP_2", "TOP", 1 },
    { 16, GearSetKind::Rider, GearSetSlot::RiderTop, "DIRTRUNNER_TOP_4", "TOP", 1 },
    { 17, GearSetKind::Rider, GearSetSlot::RiderBottom, "DIRTRUNNER_BOTTOM_1", "BOTTOM", 1 },
    { 18, GearSetKind::Rider, GearSetSlot::RiderBottom, "DIRTRUNNER_BOTTOM_2", "BOTTOM", 1 },
    { 19, GearSetKind::Rider, GearSetSlot::RiderBottom, "DIRTRUNNER_BOTTOM_4", "BOTTOM", 1 },
    { 20, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DIRTRUNNER_HELMET_1", "HELMET", 1 },
    { 21, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DIRTRUNNER_HELMET_2", "HELMET", 1 },
    { 22, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DIRTRUNNER_HELMET_4", "HELMET", 1 },
    { 23, GearSetKind::Rider, GearSetSlot::RiderBottom, "XPOLICE_BOTTOM_1", "BOTTOM", 1 },
    { 24, GearSetKind::Rider, GearSetSlot::RiderBottom, "XPOLICE_BOTTOM_2", "BOTTOM", 1 },
    { 25, GearSetKind::Rider, GearSetSlot::RiderBottom, "XPOLICE_BOTTOM_4", "BOTTOM", 1 },
    { 26, GearSetKind::Rider, GearSetSlot::RiderHelmet, "XPOLICE_HELMET_1", "HELMET", 1 },
    { 27, GearSetKind::Rider, GearSetSlot::RiderHelmet, "XPOLICE_HELMET_2", "HELMET", 1 },
    { 28, GearSetKind::Rider, GearSetSlot::RiderHelmet, "XPOLICE_HELMET_4", "HELMET", 1 },
    { 29, GearSetKind::Rider, GearSetSlot::RiderTop, "XPOLICE_TOP_1", "TOP", 1 },
    { 30, GearSetKind::Rider, GearSetSlot::RiderTop, "XPOLICE_TOP_2", "TOP", 1 },
    { 31, GearSetKind::Rider, GearSetSlot::RiderTop, "XPOLICE_TOP_4", "TOP", 1 },
    { 32, GearSetKind::Rider, GearSetSlot::RiderTop, "FMX_TOP_1", "TOP", 1 },
    { 33, GearSetKind::Rider, GearSetSlot::RiderTop, "FMX_TOP_2", "TOP", 1 },
    { 34, GearSetKind::Rider, GearSetSlot::RiderTop, "FMX_TOP_4", "TOP", 1 },
    { 35, GearSetKind::Rider, GearSetSlot::RiderBottom, "FMX_BOTTOM_1", "BOTTOM", 1 },
    { 36, GearSetKind::Rider, GearSetSlot::RiderBottom, "FMX_BOTTOM_2", "BOTTOM", 1 },
    { 37, GearSetKind::Rider, GearSetSlot::RiderBottom, "FMX_BOTTOM_4", "BOTTOM", 1 },
    { 38, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FMX_HELMET_1", "HELMET", 1 },
    { 39, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FMX_HELMET_2", "HELMET", 1 },
    { 40, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FMX_HELMET_4", "HELMET", 1 },
    { 41, GearSetKind::Rider, GearSetSlot::RiderTop, "GEOLOGIST_TOP_1", "TOP", 1 },
    { 42, GearSetKind::Rider, GearSetSlot::RiderTop, "GEOLOGIST_TOP_2", "TOP", 1 },
    { 43, GearSetKind::Rider, GearSetSlot::RiderTop, "GEOLOGIST_TOP_4", "TOP", 1 },
    { 44, GearSetKind::Rider, GearSetSlot::RiderBottom, "GEOLOGIST_BOTTOM_1", "BOTTOM", 1 },
    { 45, GearSetKind::Rider, GearSetSlot::RiderBottom, "GEOLOGIST_BOTTOM_2", "BOTTOM", 1 },
    { 46, GearSetKind::Rider, GearSetSlot::RiderBottom, "GEOLOGIST_BOTTOM_4", "BOTTOM", 1 },
    { 47, GearSetKind::Rider, GearSetSlot::RiderHelmet, "GEOLOGIST_HELMET_1", "HELMET", 1 },
    { 48, GearSetKind::Rider, GearSetSlot::RiderHelmet, "GEOLOGIST_HELMET_2", "HELMET", 1 },
    { 49, GearSetKind::Rider, GearSetSlot::RiderHelmet, "GEOLOGIST_HELMET_4", "HELMET", 1 },
    { 50, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_1", "FAIRINGS", 0 },
    { 51, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_2", "FAIRINGS", 0 },
    { 52, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_4", "FAIRINGS", 1 },
    { 53, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_8", "FAIRINGS", 1 },
    { 54, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_16", "FAIRINGS", 1 },
    { 55, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_1", "WHEELS", 1 },
    { 56, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_2", "WHEELS", 0 },
    { 57, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_4", "WHEELS", 1 },
    { 58, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_8", "WHEELS", 1 },
    { 59, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_16", "WHEELS", 1 },
    { 60, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_32", "WHEELS", 1 },
    { 61, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_64", "WHEELS", 0 },
    { 62, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_1", "WHEELS", 1 },
    { 63, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_1", "FAIRINGS", 1 },
    { 64, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_2", "FAIRINGS", 1 },
    { 65, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_4", "FAIRINGS", 1 },
    { 66, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_2", "WHEELS", 1 },
    { 67, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_4", "WHEELS", 1 },
    { 68, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_8", "WHEELS", 1 },
    { 69, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_16", "WHEELS", 1 },
    { 70, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_32", "WHEELS", 1 },
    { 71, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_64", "WHEELS", 1 },
    { 72, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_8", "FAIRINGS", 1 },
    { 73, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_16", "FAIRINGS", 1 },
    { 74, GearSetKind::Bike, GearSetSlot::BikeFairings, "MINX_FAIRINGS_1", "FAIRINGS", 0 },
    { 75, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_1", "WHEELS", 0 },
    { 76, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_2", "WHEELS", 0 },
    { 77, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_4", "WHEELS", 0 },
    { 78, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_8", "WHEELS", 0 },
    { 79, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_16", "WHEELS", 1 },
    { 80, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_32", "WHEELS", 1 },
    { 81, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_64", "WHEELS", 1 },
    { 82, GearSetKind::Bike, GearSetSlot::BikeFairings, "FAT_FAIRINGS_1", "FAIRINGS", 1 },
    { 83, GearSetKind::Bike, GearSetSlot::BikeWheels, "FAT_WHEELS_1", "WHEELS", 1 },
    { 84, GearSetKind::Bike, GearSetSlot::BikeFairings, "PAPER_FAIRINGS_1", "FAIRINGS", 0 },
    { 85, GearSetKind::Bike, GearSetSlot::BikeWheels, "PAPER_WHEELS_1", "WHEELS", 1 },
    { 86, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_1", "FAIRINGS", 1 },
    { 87, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_2", "FAIRINGS", 1 },
    { 88, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_4", "FAIRINGS", 1 },
    { 89, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_8", "FAIRINGS", 1 },
    { 90, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_1", "WHEELS", 0 },
    { 91, GearSetKind::Rider, GearSetSlot::RiderBottom, "HAZMASUIT_BOTTOM_1", "BOTTOM", 0 },
    { 92, GearSetKind::Rider, GearSetSlot::RiderHelmet, "HAZMASUIT_HELMET_1", "HELMET", 1 },
    { 93, GearSetKind::Rider, GearSetSlot::RiderTop, "HAZMASUIT_TOP_1", "TOP", 1 },
    { 96, GearSetKind::Rider, GearSetSlot::RiderHelmet, "SUPERHERO_HELMET_1", "HELMET", 1 },
    { 97, GearSetKind::Rider, GearSetSlot::RiderTop, "SUPERHERO_TOP_1", "TOP", 1 },
    { 98, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ULCCLOWN_HELMET_1", "HELMET", 1 },
    { 99, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ULCDRINK_HELMET_1", "HELMET", 0 },
    { 100, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ULCRHINO_HELMET_1", "HELMET", 1 },
    { 101, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_32", "FAIRINGS", 0 },
    { 102, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_128", "WHEELS", 0 },
    { 103, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_32", "FAIRINGS", 0 },
    { 104, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_16", "FAIRINGS", 0 },
    { 105, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_128", "WHEELS", 1 },
    { 106, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_2", "WHEELS", 1 },
    { 107, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_4", "WHEELS", 1 },
    { 108, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_8", "WHEELS", 1 },
    { 109, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_16", "WHEELS", 1 },
    { 110, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_32", "WHEELS", 1 },
    { 111, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_64", "WHEELS", 1 },
};

static constexpr size_t kGearSetCatalogCount = sizeof(kGearSetCatalog) / sizeof(kGearSetCatalog[0]);
