#pragma once

#include <cstddef>
#include <cstdint>

enum class GearSetKind {
    Rider,
    Bike
};

enum class GearSetSlot {
    RiderTop,
    RiderBottom,
    RiderHelmet,
    BikeFairings,
    BikeWheels
};

struct GearSetCatalogEntry {
    uint16_t id;
    GearSetKind kind;
    GearSetSlot slot;
    const char* genKey;
    const char* category;
    uint8_t colorPartCount;
};

static const GearSetCatalogEntry kGearSetCatalog[] = {
    { 1, GearSetKind::Rider, GearSetSlot::RiderTop, "TECHBOY_TOP_1", "TOP", 1 },
    { 2, GearSetKind::Rider, GearSetSlot::RiderTop, "TECHBOY_TOP_2", "TOP", 1 },
    { 3, GearSetKind::Rider, GearSetSlot::RiderTop, "TECHBOY_TOP_4", "TOP", 1 },
    { 4, GearSetKind::Rider, GearSetSlot::RiderBottom, "TECHBOY_BOTTOM_1", "BOTTOM", 1 },
    { 5, GearSetKind::Rider, GearSetSlot::RiderBottom, "TECHBOY_BOTTOM_2", "BOTTOM", 1 },
    { 6, GearSetKind::Rider, GearSetSlot::RiderBottom, "TECHBOY_BOTTOM_4", "BOTTOM", 1 },
    { 7, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TECHBOY_HELMET_1", "HELMET", 1 },
    { 8, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TECHBOY_HELMET_2", "HELMET", 1 },
    { 9, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TECHBOY_HELMET_4", "HELMET", 1 },
    { 10, GearSetKind::Rider, GearSetSlot::RiderHelmet, "SQUIRREL_HELMET_1", "HELMET", 0 },
    { 11, GearSetKind::Rider, GearSetSlot::RiderTop, "EVEL_TOP_1", "TOP", 1 },
    { 12, GearSetKind::Rider, GearSetSlot::RiderHelmet, "EVEL_HELMET_1", "HELMET", 1 },
    { 13, GearSetKind::Rider, GearSetSlot::RiderBottom, "EVEL_BOTTOM_1", "BOTTOM", 1 },
    { 14, GearSetKind::Rider, GearSetSlot::RiderTop, "DIRTRUNNER_TOP_1", "TOP", 1 },
    { 15, GearSetKind::Rider, GearSetSlot::RiderTop, "DIRTRUNNER_TOP_2", "TOP", 1 },
    { 16, GearSetKind::Rider, GearSetSlot::RiderTop, "DIRTRUNNER_TOP_4", "TOP", 1 },
    { 17, GearSetKind::Rider, GearSetSlot::RiderBottom, "DIRTRUNNER_BOTTOM_1", "BOTTOM", 1 },
    { 18, GearSetKind::Rider, GearSetSlot::RiderBottom, "DIRTRUNNER_BOTTOM_2", "BOTTOM", 1 },
    { 19, GearSetKind::Rider, GearSetSlot::RiderBottom, "DIRTRUNNER_BOTTOM_4", "BOTTOM", 1 },
    { 20, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DIRTRUNNER_HELMET_1", "HELMET", 1 },
    { 21, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DIRTRUNNER_HELMET_2", "HELMET", 1 },
    { 22, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DIRTRUNNER_HELMET_4", "HELMET", 1 },
    { 23, GearSetKind::Rider, GearSetSlot::RiderBottom, "XPOLICE_BOTTOM_1", "BOTTOM", 1 },
    { 24, GearSetKind::Rider, GearSetSlot::RiderBottom, "XPOLICE_BOTTOM_2", "BOTTOM", 1 },
    { 25, GearSetKind::Rider, GearSetSlot::RiderBottom, "XPOLICE_BOTTOM_4", "BOTTOM", 1 },
    { 26, GearSetKind::Rider, GearSetSlot::RiderHelmet, "XPOLICE_HELMET_1", "HELMET", 1 },
    { 27, GearSetKind::Rider, GearSetSlot::RiderHelmet, "XPOLICE_HELMET_2", "HELMET", 1 },
    { 28, GearSetKind::Rider, GearSetSlot::RiderHelmet, "XPOLICE_HELMET_4", "HELMET", 1 },
    { 29, GearSetKind::Rider, GearSetSlot::RiderTop, "XPOLICE_TOP_1", "TOP", 1 },
    { 30, GearSetKind::Rider, GearSetSlot::RiderTop, "XPOLICE_TOP_2", "TOP", 1 },
    { 31, GearSetKind::Rider, GearSetSlot::RiderTop, "XPOLICE_TOP_4", "TOP", 1 },
    { 32, GearSetKind::Rider, GearSetSlot::RiderTop, "FMX_TOP_1", "TOP", 1 },
    { 33, GearSetKind::Rider, GearSetSlot::RiderTop, "FMX_TOP_2", "TOP", 1 },
    { 34, GearSetKind::Rider, GearSetSlot::RiderTop, "FMX_TOP_4", "TOP", 1 },
    { 35, GearSetKind::Rider, GearSetSlot::RiderBottom, "FMX_BOTTOM_1", "BOTTOM", 1 },
    { 36, GearSetKind::Rider, GearSetSlot::RiderBottom, "FMX_BOTTOM_2", "BOTTOM", 1 },
    { 37, GearSetKind::Rider, GearSetSlot::RiderBottom, "FMX_BOTTOM_4", "BOTTOM", 1 },
    { 38, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FMX_HELMET_1", "HELMET", 1 },
    { 39, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FMX_HELMET_2", "HELMET", 1 },
    { 40, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FMX_HELMET_4", "HELMET", 1 },
    { 41, GearSetKind::Rider, GearSetSlot::RiderTop, "GEOLOGIST_TOP_1", "TOP", 1 },
    { 42, GearSetKind::Rider, GearSetSlot::RiderTop, "GEOLOGIST_TOP_2", "TOP", 1 },
    { 43, GearSetKind::Rider, GearSetSlot::RiderTop, "GEOLOGIST_TOP_4", "TOP", 1 },
    { 44, GearSetKind::Rider, GearSetSlot::RiderBottom, "GEOLOGIST_BOTTOM_1", "BOTTOM", 1 },
    { 45, GearSetKind::Rider, GearSetSlot::RiderBottom, "GEOLOGIST_BOTTOM_2", "BOTTOM", 1 },
    { 46, GearSetKind::Rider, GearSetSlot::RiderBottom, "GEOLOGIST_BOTTOM_4", "BOTTOM", 1 },
    { 47, GearSetKind::Rider, GearSetSlot::RiderHelmet, "GEOLOGIST_HELMET_1", "HELMET", 1 },
    { 48, GearSetKind::Rider, GearSetSlot::RiderHelmet, "GEOLOGIST_HELMET_2", "HELMET", 1 },
    { 49, GearSetKind::Rider, GearSetSlot::RiderHelmet, "GEOLOGIST_HELMET_4", "HELMET", 1 },
    { 50, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_1", "FAIRINGS", 0 },
    { 51, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_2", "FAIRINGS", 0 },
    { 52, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_4", "FAIRINGS", 1 },
    { 53, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_8", "FAIRINGS", 1 },
    { 54, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_16", "FAIRINGS", 1 },
    { 55, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_1", "WHEELS", 1 },
    { 56, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_2", "WHEELS", 0 },
    { 57, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_4", "WHEELS", 1 },
    { 58, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_8", "WHEELS", 1 },
    { 59, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_16", "WHEELS", 1 },
    { 60, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_32", "WHEELS", 1 },
    { 61, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_64", "WHEELS", 0 },
    { 62, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_1", "WHEELS", 1 },
    { 63, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_1", "FAIRINGS", 1 },
    { 64, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_2", "FAIRINGS", 1 },
    { 65, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_4", "FAIRINGS", 1 },
    { 66, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_2", "WHEELS", 1 },
    { 67, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_4", "WHEELS", 1 },
    { 68, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_8", "WHEELS", 1 },
    { 69, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_16", "WHEELS", 1 },
    { 70, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_32", "WHEELS", 1 },
    { 71, GearSetKind::Bike, GearSetSlot::BikeWheels, "CHEETAH_WHEELS_64", "WHEELS", 1 },
    { 72, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_8", "FAIRINGS", 1 },
    { 73, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_16", "FAIRINGS", 1 },
    { 74, GearSetKind::Bike, GearSetSlot::BikeFairings, "MINX_FAIRINGS_1", "FAIRINGS", 0 },
    { 75, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_1", "WHEELS", 0 },
    { 76, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_2", "WHEELS", 0 },
    { 77, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_4", "WHEELS", 0 },
    { 78, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_8", "WHEELS", 0 },
    { 79, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_16", "WHEELS", 1 },
    { 80, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_32", "WHEELS", 1 },
    { 81, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINX_WHEELS_64", "WHEELS", 1 },
    { 82, GearSetKind::Bike, GearSetSlot::BikeFairings, "FAT_FAIRINGS_1", "FAIRINGS", 1 },
    { 83, GearSetKind::Bike, GearSetSlot::BikeWheels, "FAT_WHEELS_1", "WHEELS", 1 },
    { 84, GearSetKind::Bike, GearSetSlot::BikeFairings, "PAPER_FAIRINGS_1", "FAIRINGS", 0 },
    { 85, GearSetKind::Bike, GearSetSlot::BikeWheels, "PAPER_WHEELS_1", "WHEELS", 1 },
    { 86, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_1", "FAIRINGS", 1 },
    { 87, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_2", "FAIRINGS", 1 },
    { 88, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_4", "FAIRINGS", 1 },
    { 89, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_8", "FAIRINGS", 1 },
    { 90, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_1", "WHEELS", 0 },
    { 91, GearSetKind::Rider, GearSetSlot::RiderBottom, "HAZMASUIT_BOTTOM_1", "BOTTOM", 0 },
    { 92, GearSetKind::Rider, GearSetSlot::RiderHelmet, "HAZMASUIT_HELMET_1", "HELMET", 1 },
    { 93, GearSetKind::Rider, GearSetSlot::RiderTop, "HAZMASUIT_TOP_1", "TOP", 1 },
    { 96, GearSetKind::Rider, GearSetSlot::RiderHelmet, "SUPERHERO_HELMET_1", "HELMET", 1 },
    { 97, GearSetKind::Rider, GearSetSlot::RiderTop, "SUPERHERO_TOP_1", "TOP", 1 },
    { 98, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ULCCLOWN_HELMET_1", "HELMET", 1 },
    { 99, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ULCDRINK_HELMET_1", "HELMET", 0 },
    { 100, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ULCRHINO_HELMET_1", "HELMET", 1 },
    { 101, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FAIRINGS_32", "FAIRINGS", 0 },
    { 102, GearSetKind::Bike, GearSetSlot::BikeWheels, "KINGCOBRA_WHEELS_128", "WHEELS", 0 },
    { 103, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_32", "FAIRINGS", 0 },
    { 104, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_16", "FAIRINGS", 0 },
    { 105, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_128", "WHEELS", 1 },
    { 106, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_2", "WHEELS", 1 },
    { 107, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_4", "WHEELS", 1 },
    { 108, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_8", "WHEELS", 1 },
    { 109, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_16", "WHEELS", 1 },
    { 110, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_32", "WHEELS", 1 },
    { 111, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_64", "WHEELS", 1 },
    { 772, GearSetKind::Bike, GearSetSlot::BikeWheels, "TRICKY_WHEELS_128", "WHEELS", 0 },
    { 773, GearSetKind::Bike, GearSetSlot::BikeFairings, "TRICKY_FAIRINGS_16", "FAIRINGS", 0 },
    { 774, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_32", "FAIRINGS", 0 },
    { 775, GearSetKind::Rider, GearSetSlot::RiderTop, "SUPERHERO_TOP_1", "TOP", 1 },
    { 776, GearSetKind::Rider, GearSetSlot::RiderHelmet, "SUPERHERO_HELMET_1", "HELMET", 1 },
    { 777, GearSetKind::Rider, GearSetSlot::RiderTop, "HAZMASUIT_TOP_1", "TOP", 1 },
    { 778, GearSetKind::Rider, GearSetSlot::RiderHelmet, "HAZMASUIT_HELMET_1", "HELMET", 1 },
    { 779, GearSetKind::Rider, GearSetSlot::RiderBottom, "HAZMASUIT_BOTTOM_1", "BOTTOM", 1 },
    { 887, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINDSCREW_RIM_CHEETAH", "WHEELS", 1 },
    { 888, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINDSCREW_RIM_MINX", "WHEELS", 1 },
    { 889, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINDSCREW_RIM_TRICKY", "WHEELS", 1 },
    { 890, GearSetKind::Bike, GearSetSlot::BikeWheels, "MINDSCREW_RIM_KINGCOBRA", "WHEELS", 1 },
    { 891, GearSetKind::Rider, GearSetSlot::RiderHelmet, "ROACH_HELMET_1", "HELMET", 1 },
    { 892, GearSetKind::Rider, GearSetSlot::RiderTop, "AC_ELISE_TOP_1", "TOP", 1 },
    { 893, GearSetKind::Rider, GearSetSlot::RiderHelmet, "AC_ELISE_HELMET_1", "HELMET", 1 },
    { 894, GearSetKind::Rider, GearSetSlot::RiderBottom, "AC_ELISE_BOTTOM_1", "BOTTOM", 1 },
    { 895, GearSetKind::Bike, GearSetSlot::BikeFairings, "UNICORN_BIKE_1", "FAIRINGS", 1 },
    { 896, GearSetKind::Bike, GearSetSlot::BikeFairings, "UNICORN_BIKE_1", "FAIRINGS", 1 },
    { 897, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_2_RIM_CHEETAH", "WHEELS", 1 },
    { 898, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_2_RIM_MINX", "WHEELS", 1 },
    { 899, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_2_RIM_TRICKY", "WHEELS", 1 },
    { 900, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_2_RIM_KINGCOBRA", "WHEELS", 1 },
    { 901, GearSetKind::Bike, GearSetSlot::BikeFairings, "CHEETAH_FAIRINGS_7", "FAIRINGS", 1 },
    { 902, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_RIM_TRICKY", "WHEELS", 1 },
    { 903, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_RIM_KINGCOBRA", "WHEELS", 1 },
    { 904, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_RIM_MINX", "WHEELS", 1 },
    { 905, GearSetKind::Bike, GearSetSlot::BikeWheels, "COMPONENTIAL_RIM_CHEETAH", "WHEELS", 1 },
    { 910, GearSetKind::Bike, GearSetSlot::BikeWheels, "EVILITY_RIM_CHEETAH", "WHEELS", 1 },
    { 911, GearSetKind::Bike, GearSetSlot::BikeWheels, "EVILITY_RIM_MINX", "WHEELS", 1 },
    { 912, GearSetKind::Bike, GearSetSlot::BikeWheels, "EVILITY_RIM_TRICKY", "WHEELS", 1 },
    { 913, GearSetKind::Bike, GearSetSlot::BikeWheels, "EVILITY_RIM_KINGCOBRA", "WHEELS", 0 },
    { 914, GearSetKind::Rider, GearSetSlot::RiderHelmet, "PLAGUEDOCTOR_HELMET_1", "HELMET", 1 },
    { 915, GearSetKind::Rider, GearSetSlot::RiderBottom, "MALE_ASSASSIN_BOTTOMS_1", "BOTTOM", 1 },
    { 916, GearSetKind::Rider, GearSetSlot::RiderHelmet, "MALE_ASSASSIN_HELMETS_1", "HELMET", 1 },
    { 917, GearSetKind::Rider, GearSetSlot::RiderTop, "MALE_ASSASSIN_TOPS_1", "TOP", 1 },
    { 919, GearSetKind::Rider, GearSetSlot::RiderHelmet, "HORROR_HELMET_1", "HELMET", 1 },
    { 923, GearSetKind::Rider, GearSetSlot::RiderTop, "FEMALE_OUTFIT_1_TOP_1", "TOP", 1 },
    { 924, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FEMALE_OUTFIT_1_HELMET_1", "HELMET", 1 },
    { 925, GearSetKind::Rider, GearSetSlot::RiderBottom, "FEMALE_OUTFIT_1_BOTTOM_1", "BOTTOM", 1 },
    { 926, GearSetKind::Rider, GearSetSlot::RiderTop, "FEMALE_BARBARA_TOP_1", "TOP", 1 },
    { 927, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FEMALE_BARBARA_HELMET_1", "HELMET", 1 },
    { 928, GearSetKind::Rider, GearSetSlot::RiderBottom, "FEMALE_BARBARA_BOTTOM_1", "BOTTOM", 1 },
    { 929, GearSetKind::Bike, GearSetSlot::BikeFairings, "WASP_GRIZZLY", "FAIRINGS", 1 },
    { 932, GearSetKind::Rider, GearSetSlot::RiderHelmet, "CYBORG_HELMET_1", "HELMET", 1 },
    { 933, GearSetKind::Rider, GearSetSlot::RiderHelmet, "RABBIT_HELMET_1", "HELMET", 1 },
    { 934, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DAPPER_PUG_HELMET_1", "HELMET", 1 },
    { 935, GearSetKind::Rider, GearSetSlot::RiderHelmet, "POST_APO_HELMET_1", "HELMET", 1 },
    { 936, GearSetKind::Rider, GearSetSlot::RiderBottom, "RAYMAN_BOTTOM", "BOTTOM", 1 },
    { 937, GearSetKind::Rider, GearSetSlot::RiderHelmet, "RAYMAN_HELMET", "HELMET", 1 },
    { 938, GearSetKind::Rider, GearSetSlot::RiderTop, "RAYMAN_TOP", "TOP", 1 },
    { 939, GearSetKind::Rider, GearSetSlot::RiderBottom, "BOUNTY_HUNTER_BOTTOM", "BOTTOM", 1 },
    { 940, GearSetKind::Rider, GearSetSlot::RiderHelmet, "BOUNTY_HUNTER_HELMET", "HELMET", 1 },
    { 941, GearSetKind::Rider, GearSetSlot::RiderTop, "BOUNTY_HUNTER_TOP", "TOP", 1 },
    { 942, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_RAYMAN", "FAIRINGS", 1 },
    { 943, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_FLAME", "FAIRINGS", 1 },
    { 944, GearSetKind::Bike, GearSetSlot::BikeFairings, "80S_MINX", "FAIRINGS", 1 },
    { 945, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_AC", "FAIRINGS", 1 },
    { 950, GearSetKind::Rider, GearSetSlot::RiderTop, "LUMITECH_FEMALE_TOPS_1", "TOP", 1 },
    { 951, GearSetKind::Rider, GearSetSlot::RiderHelmet, "LUMITECH_FEMALE_HELMET_1", "HELMET", 1 },
    { 952, GearSetKind::Rider, GearSetSlot::RiderBottom, "LUMITECH_FEMALE_BOTTOM_1", "BOTTOM", 1 },
    { 956, GearSetKind::Rider, GearSetSlot::RiderHelmet, "TKO_PANDA_HELMET_1", "HELMET", 1 },
    { 957, GearSetKind::Rider, GearSetSlot::RiderTop, "FEMALE_INDIAN_TOP_1", "TOP", 1 },
    { 958, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FEMALE_INDIAN_HELMET_1", "HELMET", 1 },
    { 959, GearSetKind::Rider, GearSetSlot::RiderBottom, "FEMALE_INDIAN_BOTTOM_1", "BOTTOM", 1 },
    { 960, GearSetKind::Rider, GearSetSlot::RiderTop, "FEMALE_ASSASSIN_TOP_1", "TOP", 1 },
    { 961, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FEMALE_ASSASSIN_HELMET_1", "HELMET", 1 },
    { 962, GearSetKind::Rider, GearSetSlot::RiderBottom, "FEMALE_ASSASSIN_BOTTOM_1", "BOTTOM", 1 },
    { 963, GearSetKind::Rider, GearSetSlot::RiderTop, "FEMALE_OFFICER_TOP_1", "TOP", 1 },
    { 964, GearSetKind::Rider, GearSetSlot::RiderHelmet, "FEMALE_OFFICER_HELMET_1", "HELMET", 1 },
    { 965, GearSetKind::Rider, GearSetSlot::RiderBottom, "FEMALE_OFFICER_BOTTOM_1", "BOTTOM", 1 },
    { 966, GearSetKind::Bike, GearSetSlot::BikeFairings, "GOLD_PITVIPER", "FAIRINGS", 1 },
    { 967, GearSetKind::Bike, GearSetSlot::BikeFairings, "WD_PITVIPER", "FAIRINGS", 1 },
    { 968, GearSetKind::Bike, GearSetSlot::BikeFairings, "WILDCAT_RABBIT", "FAIRINGS", 1 },
    { 969, GearSetKind::Bike, GearSetSlot::BikeFairings, "DONKEY_BIKE_1", "FAIRINGS", 1 },
    { 970, GearSetKind::Bike, GearSetSlot::BikeWheels, "BASIC_RIM_DONKEY", "WHEELS", 1 },
    { 971, GearSetKind::Bike, GearSetSlot::BikeFairings, "STICKER_RABBIT", "FAIRINGS", 1 },
    { 973, GearSetKind::Bike, GearSetSlot::BikeFairings, "COMIC_PITVIPER", "FAIRINGS", 1 },
    { 974, GearSetKind::Bike, GearSetSlot::BikeFairings, "KINGCOBRA_HORROR", "FAIRINGS", 1 },
    { 975, GearSetKind::Rider, GearSetSlot::RiderBottom, "DAPPER_BOTTOMS_1", "BOTTOM", 1 },
    { 976, GearSetKind::Rider, GearSetSlot::RiderHelmet, "DAPPER_HELMETS_1", "HELMET", 1 },
    { 977, GearSetKind::Rider, GearSetSlot::RiderTop, "DAPPER_TOPS_1", "TOP", 1 },
    { 978, GearSetKind::Bike, GearSetSlot::BikeWheels, "SPITTING_RIM_CHEETAH", "WHEELS", 1 },
    { 979, GearSetKind::Bike, GearSetSlot::BikeWheels, "SPITTING_RIM_MINX", "WHEELS", 1 },
    { 980, GearSetKind::Bike, GearSetSlot::BikeWheels, "SPITTING_RIM_TRICKY", "WHEELS", 1 },
    { 981, GearSetKind::Bike, GearSetSlot::BikeWheels, "SPITTING_RIM_KINGCOBRA", "WHEELS", 1 },
    { 982, GearSetKind::Rider, GearSetSlot::RiderHelmet, "PITVIPER_HELMET_1", "HELMET", 1 },
    { 983, GearSetKind::Bike, GearSetSlot::BikeWheels, "CLOCKWORK_RIM_CHEETAH", "WHEELS", 1 },
    { 984, GearSetKind::Bike, GearSetSlot::BikeWheels, "CLOCKWORK_RIM_MINX", "WHEELS", 1 },
    { 985, GearSetKind::Bike, GearSetSlot::BikeWheels, "CLOCKWORK_RIM_TRICKY", "WHEELS", 1 },
    { 986, GearSetKind::Bike, GearSetSlot::BikeWheels, "CLOCKWORK_RIM_KINGCOBRA", "WHEELS", 0 },
    { 991, GearSetKind::Rider, GearSetSlot::RiderTop, "POSTAPO_FEMALE_TOP_1", "TOP", 1 },
    { 992, GearSetKind::Rider, GearSetSlot::RiderHelmet, "POSTAPO_FEMALE_HELMET_1", "HELMET", 1 },
    { 993, GearSetKind::Rider, GearSetSlot::RiderBottom, "POSTAPO_FEMALE_BOTTOM_1", "BOTTOM", 1 },
    { 998, GearSetKind::Rider, GearSetSlot::RiderBottom, "AC_ARNO_BOTTOMS_1", "BOTTOM", 1 },
    { 999, GearSetKind::Rider, GearSetSlot::RiderHelmet, "AC_ARNO_HELMETS_1", "HELMET", 1 },
    { 1000, GearSetKind::Rider, GearSetSlot::RiderTop, "AC_ARNO_TOPS_1", "TOP", 1 },
    { 1001, GearSetKind::Rider, GearSetSlot::RiderTop, "WD_CLARA_TOP_1", "TOP", 1 },
    { 1002, GearSetKind::Rider, GearSetSlot::RiderHelmet, "WD_CLARA_HELMET_1", "HELMET", 1 },
    { 1003, GearSetKind::Rider, GearSetSlot::RiderBottom, "WD_CLARA_BOTTOM_1", "BOTTOM", 1 },
    { 1004, GearSetKind::Rider, GearSetSlot::RiderHelmet, "BAGGIE_HELMET_1", "HELMET", 1 },
    { 1005, GearSetKind::Rider, GearSetSlot::RiderBottom, "WD_AIDEN_BOTTOMS_1", "BOTTOM", 1 },
    { 1006, GearSetKind::Rider, GearSetSlot::RiderHelmet, "WD_AIDEN_HELMETS_1", "HELMET", 1 },
    { 1007, GearSetKind::Rider, GearSetSlot::RiderTop, "WD_AIDEN_TOPS_1", "TOP", 1 },
    { 1008, GearSetKind::Bike, GearSetSlot::BikeFairings, "EVO_CHEETAH", "FAIRINGS", 1 },
    { 1009, GearSetKind::Bike, GearSetSlot::BikeWheels, "GRINDER_RIM_CHEETAH", "WHEELS", 1 },
    { 1010, GearSetKind::Bike, GearSetSlot::BikeWheels, "GRINDER_RIM_MINX", "WHEELS", 1 },
    { 1011, GearSetKind::Bike, GearSetSlot::BikeWheels, "GRINDER_RIM_TRICKY", "WHEELS", 1 },
    { 1012, GearSetKind::Bike, GearSetSlot::BikeWheels, "GRINDER_RIM_KINGCOBRA", "WHEELS", 0 },
    { 1013, GearSetKind::Bike, GearSetSlot::BikeWheels, "HOLOGRAPH_RIM_CHEETAH", "WHEELS", 1 },
    { 1014, GearSetKind::Bike, GearSetSlot::BikeWheels, "HOLOGRAPH_RIM_MINX", "WHEELS", 1 },
    { 1015, GearSetKind::Bike, GearSetSlot::BikeWheels, "HOLOGRAPH_RIM_TRICKY", "WHEELS", 1 },
    { 1016, GearSetKind::Bike, GearSetSlot::BikeWheels, "HOLOGRAPH_RIM_KINGCOBRA", "WHEELS", 1 },
    { 1017, GearSetKind::Bike, GearSetSlot::BikeWheels, "SUMIE_RIM_CHEETAH", "WHEELS", 1 },
    { 1018, GearSetKind::Bike, GearSetSlot::BikeWheels, "SUMIE_RIM_MINX", "WHEELS", 1 },
    { 1019, GearSetKind::Bike, GearSetSlot::BikeWheels, "SUMIE_RIM_TRICKY", "WHEELS", 1 },
    { 1020, GearSetKind::Bike, GearSetSlot::BikeWheels, "SUMIE_RIM_KINGCOBRA", "WHEELS", 0 },
};

static constexpr size_t kGearSetCatalogCount = sizeof(kGearSetCatalog) / sizeof(kGearSetCatalog[0]);
